### ISSUE TITLE
[Feature] Add Yahoo Support

### ISSUE THREAD

**Issue by saglaniharsh** [ashawe/searchViaTerminal#2]
Add yahoo support for images, videos, news and answers

**Comment by ghost** [comment]
Hellow @ashawe I have make your demand, i think this is you want :smile:

**Comment by ghost** [comment]
Hello @ashawe it's possible to add the "hacktoberfest-accepted" stickers in the PR ?

**Comment by saglaniharsh** [comment]
> 
> 
> Hello @ashawe it's possible to add the "hacktoberfest-accepted" stickers in the PR ?

Your PR was merged. It should be counted for your hacktoberfest PRs
